### ISSUE TITLE
Burning Tree Problem - How much a Binary Tree will take to burn a tree problem

### ISSUE THREAD

**Issue by bhavya-sharma26** [SR-Sunny-Raj/Hacktoberfest2022-for-everyone#122]

**Comment by bhavya-sharma26** [comment]
can you please this task to me

**Comment by hiteshdaga** [comment]
Hi, can you please assign this task to me?
I am participating in Hacktoberfest for the first time and am from the IT field.

**Comment by Sakshi2002-Sinha** [comment]
Hello, Can you please assign this issue to me?
Thanks in advance :)

**Comment by CODER-AsHuToSh** [comment]
Hello, Can you please assign this issue to me?
