### ISSUE TITLE
double linked list

### ISSUE THREAD

**Issue by VishalVR-21** [SR-Sunny-Raj/Hacktoberfest2022-for-everyone#127]

**Comment by bhavya-sharma26** [comment]
can u please assign this task to me?
I am participating in Hacktoberfest for the first time.

**Comment by rajdeepsri** [comment]
can you please assign this issue to me? I have good knowledge on Data Structures and currently studying linked lists

**Comment by hiteshdaga** [comment]
Hi, can you please assign this task to me?
I am participating in Hacktoberfest for the first time and am from the IT field.

**Comment by Sakshi2002-Sinha** [comment]
Hello, Can you please assign this issue to me? 
Thanks in advance :)

**Comment by milind64** [comment]
Hi, there @VishalVR-21 
Can you please assign me this task ?
Issue No.- #127

**Comment by sp-gits** [comment]
**can you assign this issue to me ?**

**Comment by VishalVR-21** [comment]
sorry guys i cannot assign as the I am not the maintainer I have just stated a issue.
