### ISSUE TITLE
Want to add "DRUM KIT" project in "WEB DEVELOPMENT" folder.

### ISSUE THREAD

**Issue by Ayu1C** [SR-Sunny-Raj/Hacktoberfest2022-for-everyone#130]
Hey @SR-Sunny-Raj !

I want to add the project "Drum Kit" in the web development folder.
This drum kit has various instruments displayed with buttons to get the sound .
It can be played by either clicking on buttons or by entering the alphabet corresponding to the sound.
![Drum kit snap](https://user-images.githubusercontent.com/102305307/195136107-bbb55dc9-131d-49f2-b909-48a636aba52b.PNG)

Please assign me this issue and add the label "**Hacktoberfest**" to it.

**Comment by Sakshi2002-Sinha** [comment]
Hello, Can you please assign this issue to me?
Thanks in advance :)
