### ISSUE TITLE
want to add code remove duplicates in unsorted linked list

### ISSUE THREAD

**Issue by rajdeepsri** [SR-Sunny-Raj/Hacktoberfest2022-for-everyone#142]
can you please assign this issue to me? it is my first time participating in hacktoberfest

**Comment by rajdeepsri** [comment]
@SR-Sunny-Raj please assign this to me

**Comment by hiteshdaga** [comment]
Hi, can you please assign this task to me?
I am participating in Hacktoberfest for the first time and am from the IT field.

**Comment by Sakshi2002-Sinha** [comment]
Hello, Can you please assign this issue to me?
Thanks in advance :)

**Comment by RiyaArora02** [comment]
Hii sir can you assign this issue to me I would like to contribute in it

**Comment by HarshitaSingh828** [comment]
Hi, can you assign this to me?
