### ISSUE TITLE
Adding A tic- tac-toe game in project

### ISSUE THREAD

**Issue by Nav21000** [SR-Sunny-Raj/Hacktoberfest2022-for-everyone#166]

**Comment by Ajit619** [comment]
I have very optimal code please assign me I will amplify your task

**Comment by jawadkhanpk** [comment]
Hey I have strong profile in DSA
I won lot of Hackathons in it.
Please Assign me this issue so that I can make my contribution to it.
Thanks

**Comment by Spandan2003** [comment]
Hi, 
I am trying to make a contribution for the first time. I have created a tic-tac-toe game in Python for fun and would be happy to add it to this project. How should I proceed?
Link: [Tic Tac Toe](https://github.com/Spandan2003/tic-tac-toe-game)
