### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by NaMiKA0305** [SR-Sunny-Raj/Hacktoberfest2022-for-everyone#6]
this error is coming while pushing the repo

remote: Permission to SR-Sunny-Raj/Hacktoberfest2022-for-everyone.git denied to NaMiKA0305.
fatal: unable to access 'https://github.com/SR-Sunny-Raj/Hacktoberfest2022-for-everyone.git/': The requested URL returned error: 403

**Comment by SR-Sunny-Raj** [comment]
Access this repository https://github.com/SR-Sunny-Raj/Hacktoberfest2022-for-everyone/ and make your contribution. If any further error occurs, do inform me here.

**Comment by NaMiKA0305** [comment]
So what you want to tell me? Actually sir , we tried so many times to add
that repo but that didn't work. Plzz help me to add repo.

**Comment by SR-Sunny-Raj** [comment]
Hey @NaMiKA0305 I don't know what problem you are facing as I tried to make a PR to this repo using another account and I was able to do so. so it's a fault from your side. Please follow these steps to make your contribution -> 1) Move to the directory in which you want to make your contribution. 2) There you need to click on add file button and from the dropdown select "Create new file" and then write the name of your file and add the codes in the file and at the bottom click on propose new file. If you still face any difficulty please inform me here.
